# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medisurf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatives',
            name='age_grp',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alternatives',
            name='area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alternatives',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alternatives',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='alternatives',
            name='sex',
            field=models.CharField(default='', max_length=2),
        ),
    ]
