# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medisurf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternatives',
            old_name='alernative',
            new_name='alternative',
        ),
    ]
